name: Upload-Onedriver
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      path:
        description: '下载路径'
        required: true
        default: 'PikPak Tutorial.mp4'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create Config'
        run: |
          echo 'username:${{ secrets.USERNAME }}
          password:${{ secrets.PASSWORD }}' >> config.yml
          cat config.yml
      - name: 'Download file from PikPak'
        run: |
          ls
          chmod a+x pikpakcli
          ./pikpakcli download -p ${{ github.event.inputs.path }}
          ls

